<?php

namespace App\Models;

use CodeIgniter\Model;

class Rm11a2TimbangModel extends Model
{
    protected $table         = 'rm11a2_timbang';
    protected $primaryKey    = 'id';

    protected $allowedFields = [
        // --- HEADER / SBAR & SITUASI ---
        'noRawat',
        'dpjp',
        'unitLain',
        'diagnosaMedis',
        'situasi',
        'isiKelas',

        // --- KOLOM KIRI (PENYERAHAN DARI RUANGAN) ---
        'diagnosaPra',
        'rencanaOperasi',
        'rpd',
        'isiRpdLainnya',
        'isolasi',
        'isiIsolasiLainnya',
        'alergi',
        'isiAlergi',
        'darahStatus',
        'jumlahDarah',
        'darahDetail',
        'isiPackJenis',
        'isiGolonganDarah',
        'markingStatus',
        'markingKondisi',
        'informedConsent',
        'labStatus',
        'isiLabJml',
        'perhatianKhusus',
        'isiHb',
        'isiBun',
        'isiPkLainLain',
        'isiAlbumin',
        'isiKreatinin',
        'fotoStatus',
        'isiFotoJml',
        'fotoDetail',
        'isiRontgenKet',
        'isiRontgenJml',
        'isiUsgKet',
        'isiUsgJml',
        'isiBofJml',
        'isiNst',
        'isiEchoJml',
        'isiIvpJml',
        'isiEkgJml',
        'isiFotoLainnya',
        'isiTdSistole',
        'isiTdDiastole',
        'isiSuhu',
        'isiRr',
        'isiNadi',
        'puasaStatus',
        'isiPuasaJam',
        'lavementStatus',
        'isiLavementKet',
        'tamponAnus',
        'scerenStatus',
        'gigiPalsu',
        'isiGigiDibawaOleh',
        'kesadaran',
        'isiKesadaranLain',
        'keluargaTunggu',
        'isiKontakPerson',
        'isiTelpHubungi',

        // --- ASSESSMENT, RECOMMENDATION & PETUGAS (SISI KIRI) ---
        'assesment',
        'didampingi',
        'alatTransport',
        'medikasi',
        'waktu',
        'pengantar',
        'penerima',

        // --- KOLOM KANAN (PENERIMAAN DI OK) ---
        'diagnosaPra2',
        'rencanaOperasi2',
        'rpd2',
        'isiRpdLainnya2',
        'isolasi2',
        'isiIsolasiLainnya2',
        'alergi2',
        'isiAlergi2',
        'darahStatus2',
        'jumlahDarah2',
        'darahDetail2',
        'isiPackJenis2',
        'isiGolonganDarah2',
        'markingStatus2',
        'markingKondisi2',
        'informedConsent2',
        'labStatus2',
        'isiLabJml2',
        'perhatianKhusus2',
        'isiHb2',
        'isiBun2',
        'isiPkLainLain2',
        'isiAlbumin2',
        'isiKreatinin2',
        'fotoStatus2',
        'isiFotoJml2',
        'fotoDetail2',
        'isiRontgenKet2',
        'isiRontgenJml2',
        'isiUsgKet2',
        'isiUsgJml2',
        'isiBofJml2',
        'isiNst2',
        'isiEchoJml2',
        'isiIvpJml2',
        'isiEkgJml2',
        'isiFotoLainnya2',
        'isiTdSistole2',
        'isiTdDiastole2',
        'isiSuhu2',
        'isiRr2',
        'isiNadi2',
        'puasaStatus2',
        'isiPuasaJam2',
        'lavementStatus2',
        'isiLavementKet2',
        'tamponAnus2',
        'scerenStatus2',
        'gigiPalsu2',
        'isiGigiDibawaOleh2',
        'kesadaran2',
        'isiKesadaranLain2',
        'keluargaTunggu2',
        'isiKontakPerson2',
        'isiTelpHubungi2',

        // --- ASSESSMENT, RECOMMENDATION & PETUGAS (SISI KANAN / SUFFIX 2) ---
        'assesment2',
        'didampingi2',
        'alatTransport2',
        'medikasi2',
        'waktu2',
        'pengantar2',
        'penerima2',

        // --- Riwayat Transfusi 1 ---
        'riwayatTranfusi',
        'tglTranfusi',
        'jenisTranfusi',
        'golTranfusi',
        'jumlahTranfusi',

        // --- Riwayat Transfusi 2 ---
        'riwayatTranfusi2',
        'tglTranfusi2',
        'jenisTranfusi2',
        'golTranfusi2',
        'jumlahTranfusi2',

        'ttdPengantar',
        'ttdPenerima',
        'ttdPengantar2',
        'ttdPenerima2',

    ];
}
